/**
 * Curated Lucide icons for KarakeepFE list customization
 * Icons organized by category for easy browsing
 */

export const CURATED_ICONS = {
  general: [
    "bookmark",
    "bookmark-check",
    "bookmark-plus",
    "folder",
    "folder-open",
    "star",
    "heart",
    "tag",
    "inbox",
    "archive",
    "file",
    "file-text",
    "layout-grid",
    "layout-list",
    "grid-3x3",
  ],
  tech: [
    "monitor",
    "server",
    "hard-drive",
    "cpu",
    "database",
    "cloud",
    "wifi",
    "bluetooth",
    "smartphone",
    "tablet",
    "laptop",
    "keyboard",
    "mouse",
    "usb",
  ],
  dev: [
    "code",
    "code-2",
    "terminal",
    "git-branch",
    "git-commit",
    "git-merge",
    "git-pull-request",
    "bug",
    "wrench",
    "hammer",
    "package",
    "box",
    "blocks",
    "component",
  ],
  communication: [
    "mail",
    "message-circle",
    "message-square",
    "send",
    "phone",
    "video",
    "mic",
    "radio",
    "rss",
    "podcast",
    "megaphone",
    "bell",
  ],
  media: [
    "image",
    "film",
    "music",
    "play-circle",
    "headphones",
    "camera",
    "video",
    "volume-2",
    "disc",
    "tv",
    "radio",
  ],
  business: [
    "briefcase",
    "building",
    "building-2",
    "chart-bar",
    "chart-line",
    "chart-pie",
    "trending-up",
    "trending-down",
    "dollar-sign",
    "credit-card",
    "shopping-cart",
    "shopping-bag",
    "receipt",
  ],
  personal: [
    "home",
    "user",
    "users",
    "calendar",
    "clock",
    "coffee",
    "book",
    "book-open",
    "newspaper",
    "pen-tool",
    "palette",
    "scissors",
    "shirt",
    "utensils",
    "dumbbell",
    "gamepad",
    "plane",
    "map",
  ],
  navigation: [
    "arrow-right",
    "arrow-left",
    "arrow-up",
    "arrow-down",
    "chevron-right",
    "chevron-left",
    "chevron-up",
    "chevron-down",
    "compass",
    "map-pin",
    "navigation",
    "globe",
    "external-link",
  ],
  misc: [
    "sparkles",
    "zap",
    "flame",
    "sun",
    "moon",
    "circle",
    "square",
    "triangle",
    "hexagon",
    "lightbulb",
    "target",
    "flag",
    "award",
    "trophy",
    "shield",
    "lock",
    "unlock",
    "eye",
    "settings",
    "sliders",
  ],
} as const;

/**
 * Flat array of all curated icons for search functionality
 */
export const ALL_ICONS = Object.values(CURATED_ICONS).flat();

/**
 * Human-readable labels for icon names
 */
export const ICON_LABELS: Record<string, string> = {
  // General
  bookmark: "Bookmark",
  "bookmark-check": "Bookmark Check",
  "bookmark-plus": "Bookmark Plus",
  folder: "Folder",
  "folder-open": "Folder Open",
  star: "Star",
  heart: "Heart",
  tag: "Tag",
  inbox: "Inbox",
  archive: "Archive",
  file: "File",
  "file-text": "File Text",
  "layout-grid": "Grid Layout",
  "layout-list": "List Layout",
  "grid-3x3": "Grid",

  // Tech
  monitor: "Monitor",
  server: "Server",
  "hard-drive": "Hard Drive",
  cpu: "CPU",
  database: "Database",
  cloud: "Cloud",
  wifi: "WiFi",
  bluetooth: "Bluetooth",
  smartphone: "Smartphone",
  tablet: "Tablet",
  laptop: "Laptop",
  keyboard: "Keyboard",
  mouse: "Mouse",
  usb: "USB",

  // Dev
  code: "Code",
  "code-2": "Code Alt",
  terminal: "Terminal",
  "git-branch": "Git Branch",
  "git-commit": "Git Commit",
  "git-merge": "Git Merge",
  "git-pull-request": "Pull Request",
  bug: "Bug",
  wrench: "Wrench",
  hammer: "Hammer",
  package: "Package",
  box: "Box",
  blocks: "Blocks",
  component: "Component",

  // Communication
  mail: "Mail",
  "message-circle": "Message Circle",
  "message-square": "Message Square",
  send: "Send",
  phone: "Phone",
  video: "Video",
  mic: "Microphone",
  radio: "Radio",
  rss: "RSS",
  podcast: "Podcast",
  megaphone: "Megaphone",
  bell: "Bell",

  // Media
  image: "Image",
  film: "Film",
  music: "Music",
  "play-circle": "Play",
  headphones: "Headphones",
  camera: "Camera",
  "volume-2": "Volume",
  disc: "Disc",
  tv: "TV",

  // Business
  briefcase: "Briefcase",
  building: "Building",
  "building-2": "Building Alt",
  "chart-bar": "Bar Chart",
  "chart-line": "Line Chart",
  "chart-pie": "Pie Chart",
  "trending-up": "Trending Up",
  "trending-down": "Trending Down",
  "dollar-sign": "Dollar",
  "credit-card": "Credit Card",
  "shopping-cart": "Shopping Cart",
  "shopping-bag": "Shopping Bag",
  receipt: "Receipt",

  // Personal
  home: "Home",
  user: "User",
  users: "Users",
  calendar: "Calendar",
  clock: "Clock",
  coffee: "Coffee",
  book: "Book",
  "book-open": "Book Open",
  newspaper: "Newspaper",
  "pen-tool": "Pen",
  palette: "Palette",
  scissors: "Scissors",
  shirt: "Shirt",
  utensils: "Utensils",
  dumbbell: "Dumbbell",
  gamepad: "Gamepad",
  plane: "Plane",
  map: "Map",

  // Navigation
  "arrow-right": "Arrow Right",
  "arrow-left": "Arrow Left",
  "arrow-up": "Arrow Up",
  "arrow-down": "Arrow Down",
  "chevron-right": "Chevron Right",
  "chevron-left": "Chevron Left",
  "chevron-up": "Chevron Up",
  "chevron-down": "Chevron Down",
  compass: "Compass",
  "map-pin": "Map Pin",
  navigation: "Navigation",
  globe: "Globe",
  "external-link": "External Link",

  // Misc
  sparkles: "Sparkles",
  zap: "Zap",
  flame: "Flame",
  sun: "Sun",
  moon: "Moon",
  circle: "Circle",
  square: "Square",
  triangle: "Triangle",
  hexagon: "Hexagon",
  lightbulb: "Lightbulb",
  target: "Target",
  flag: "Flag",
  award: "Award",
  trophy: "Trophy",
  shield: "Shield",
  lock: "Lock",
  unlock: "Unlock",
  eye: "Eye",
  settings: "Settings",
  sliders: "Sliders",
};

/**
 * Type for icon category keys
 */
export type IconCategory = keyof typeof CURATED_ICONS;

/**
 * Type for all valid icon names
 */
export type IconName = (typeof ALL_ICONS)[number];
